import { Document, Packer, Paragraph, TextRun, HeadingLevel, AlignmentType } from "docx";

export const generateWritMasterSheet = async (claims: string[]): Promise<Buffer> => {
  const doc = new Document({
    sections: [
      {
        properties: {},
        children: [
          new Paragraph({
            text: "APPLICATION FOR A WRIT OF HABEAS CORPUS",
            heading: HeadingLevel.TITLE,
            alignment: AlignmentType.CENTER,
          }),
          new Paragraph({
            text: "IN THE COURT OF CRIMINAL APPEALS OF TEXAS",
            heading: HeadingLevel.HEADING_1,
            alignment: AlignmentType.CENTER,
          }),
          new Paragraph({
            text: "\n",
          }),
          new Paragraph({
            text: "TABLE OF AUTHORITIES",
            heading: HeadingLevel.HEADING_2,
          }),
          // Mock Table of Authorities. In production, this parses the LangGraph citations state array.
          new Paragraph({
            children: [
              new TextRun({ text: "Ex parte Smith, 123 S.W.3d 456 (Tex. Crim. App. 2004)........................ 4", italics: true }),
            ],
          }),
          new Paragraph({
            text: "\n",
          }),
          new Paragraph({
            text: "GROUNDS FOR RELIEF",
            heading: HeadingLevel.HEADING_2,
          }),
          // Map the CREAC formatted claims generated by the LangGraph Writ Formatter
          ...claims.map(claim => new Paragraph({
            children: [
              // Use standard legal formatting: 14pt font (28 half-points), Times New Roman
              new TextRun({ text: claim, size: 28, font: "Times New Roman" }), 
            ],
            spacing: {
              line: 480, // Double spaced
            }
          })),
        ],
      },
    ],
  });

  return await Packer.toBuffer(doc);
};
